name: AWS Amazon Linux 2 3.7.9
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.13
    - name: Install dependencies
      run: |
        make install-aws
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Format
      run: |
        make format
